### ISSUE TITLE
errors occurred during building

### ISSUE THREAD

**Issue by ghost** [containers/conmon#275]
I have encountered a error  building from source code.   Is my gcc version mismatched?

steps:

1.git clone ...
2. make 

os :  ubuntu16.04 
gcc : 5.4.0

![image](https://user-images.githubusercontent.com/33537489/121305157-da6aa480-c92f-11eb-852b-7189d56ddaaa.png)

**Comment by haircommander** [comment]
interesting, this should have been fixed in https://github.com/containers/conmon/pull/268
does your version have that commit?

**Comment by ccnankai** [comment]
I pulled the latest code. 
![image](https://user-images.githubusercontent.com/33537489/121471675-aad0a080-c9f2-11eb-8151-dfc7723ed3ad.png)

**Comment by haircommander** [comment]
@giuseppe any ideas?

**Comment by giuseppe** [comment]
could you try to apply the following patch?

```diff
$ git diff
diff --git a/src/seccomp_notify.h b/src/seccomp_notify.h
index 9dda848..de1d441 100644
--- a/src/seccomp_notify.h
+++ b/src/seccomp_notify.h
@@ -3,6 +3,10 @@
 
 #include "seccomp_notify_plugin.h"
 
+#ifndef SECCOMP_RET_USER_NOTIF
+#undef USE_SECCOMP
+#endif
+
 #if USE_SECCOMP
 
 struct seccomp_notify_context_s;
```

**Comment by ccnankai** [comment]
@giuseppe 
After applying this patch, this error is still reported when compiling. It may be that there is a problem with my system environment, let me troubleshoot again. 
Thank you very much.

![image](https://user-images.githubusercontent.com/33537489/121623864-0d817500-caa3-11eb-8f66-bddb9dd0f539.png)

![image](https://user-images.githubusercontent.com/33537489/121623896-20944500-caa3-11eb-9857-8fa31d3ff608.png)

**Comment by giuseppe** [comment]
this is what I get on Ubuntu 16.04:

```
/usr/include/seccomp.h:#define SECCOMP_RET_USER_NOTIF	0x7fc00000U
root@df988d928f75:/conmon# cat /etc/issue
Ubuntu 16.04.7 LTS \n \l

root@df988d928f75:/conmon# grep -r SECCOMP_RET_USER_NOTIF /usr/include/
/usr/include/seccomp.h:/* SECCOMP_RET_USER_NOTIF was added in kernel v5.0. */
/usr/include/seccomp.h:#ifndef SECCOMP_RET_USER_NOTIF
/usr/include/seccomp.h:#define SECCOMP_RET_USER_NOTIF	0x7fc00000U
```

Altough we need this patch to address an issue when libseccomp is not installed:

```diff
diff --git a/src/seccomp_notify.c b/src/seccomp_notify.c
index 58f4a16..75737d0 100644
--- a/src/seccomp_notify.c
+++ b/src/seccomp_notify.c
@@ -6,7 +6,6 @@
 #endif
 
 #include <errno.h>
-#include <seccomp.h>
 #include <sys/ioctl.h>
 #include <linux/seccomp.h>
 #include <sys/sysmacros.h>
@@ -22,6 +21,7 @@
 #include "seccomp_notify.h"
 
 #if USE_SECCOMP
+#include <seccomp.h>
 
 #ifndef SECCOMP_USER_NOTIF_FLAG_CONTINUE
 #define SECCOMP_USER_NOTIF_FLAG_CONTINUE (1UL << 0)
diff --git a/src/seccomp_notify.h b/src/seccomp_notify.h
index 9dda848..de1d441 100644
--- a/src/seccomp_notify.h
+++ b/src/seccomp_notify.h
@@ -3,6 +3,10 @@
 
 #include "seccomp_notify_plugin.h"
 
+#ifndef SECCOMP_RET_USER_NOTIF
+#undef USE_SECCOMP
+#endif
+
 #if USE_SECCOMP
 
 struct seccomp_notify_context_s;
diff --git a/src/seccomp_notify_plugin.h b/src/seccomp_notify_plugin.h
index 562957f..1b14a5f 100644
--- a/src/seccomp_notify_plugin.h
+++ b/src/seccomp_notify_plugin.h
@@ -2,6 +2,10 @@
 
 #include <linux/seccomp.h>
 
+#ifndef SECCOMP_RET_USER_NOTIF
+#undef USE_SECCOMP
+#endif
+
 #if USE_SECCOMP
 
 struct seccomp_notify_conf_s {
```

**Comment by giuseppe** [comment]
can you show the output for `# grep -r "seccomp_notif_resp" /usr/include/` ?

**Comment by giuseppe** [comment]
we could add a check for `seccomp_notif_resp` but since it is available in Ubuntu 16.04, I think it is easier if we understand what is going on there and why it doesn't exist for you.  Have you updated the system?

**Comment by ccnankai** [comment]
My result :
cat /etc/issue :
Ubuntu 16.04.7 LTS \n \l

grep -r "seccomp_notif_resp" /usr/include/ 
![1623571505740](https://user-images.githubusercontent.com/33537489/121799867-364f6900-cc61-11eb-8db8-f33f290bfa85.jpg)

grep -r SECCOMP_RET_USER_NOTIF /usr/include/

![1623571184801](https://user-images.githubusercontent.com/33537489/121799871-4404ee80-cc61-11eb-86f4-1fdbe7b7e426.jpg)


If it really doesn't work, I am going to upgrade the system to ubuntu18.04, I am a novice.
 Thank you very much.

**Comment by giuseppe** [comment]
so seccomp_notif_resp is defined as part of `/usr/include/seccomp.h`.

Could you try adding `#include <seccomp.h>`to the `seccomp_notify_plugin.h` file?

**Comment by ccnankai** [comment]
Do I still use the patch above?   Did I add this clause correctly?
![image](https://user-images.githubusercontent.com/33537489/122065493-92aeb600-ce24-11eb-9cc4-b449bb288dc8.png)

![image](https://user-images.githubusercontent.com/33537489/122065743-c4278180-ce24-11eb-93a5-4ae49075d7b0.png)

**Comment by giuseppe** [comment]
seccomp_notif_sizes seems still missing.

What do you see with `grep -r "seccomp_notif_sizes" /usr/include/`?

Is your OS fully updated (did you run `apt-get update && apt-get upgrade`)?

**Comment by ccnankai** [comment]
The result is empty.

![image](https://user-images.githubusercontent.com/33537489/122074216-9bef5100-ce2b-11eb-841d-db0c8917a78d.png)

This error  wastes too much of your time. I'm really sorry, I closed this question. It should be that the OS has not been completely updatedI .will upgrade the system again. Thank you very much.

**Comment by haircommander** [comment]
actually, it's likely you'll run into it on 18.04, as we need kernel 5.9 or greater for proper seccomp notify support. I think this should be fixed

**Comment by ccnankai** [comment]
@haircommander 
Got it .
Thank you very much.
